## <center>Synchronous Computing: Heat Exchange</center>
### <center> Linh B. Ngo </center>
### <center> CPSC 3620 </center>

<center> <img src="pictures/heatexchange1.png" width="700"/> 
</center>

<center> <img src="pictures/heatexchange2.png" width="700"/> 
</center>

<center> <img src="pictures/heatexchange3.png" width="700"/> 
</center>

<center> <img src="pictures/heatexchange4.png" width="700"/> 
</center>

<center> <img src="pictures/heatexchange5.png" width="700"/> 
</center>

#### <center> Row Exchange

- All processes interact with adjacent neighbors to exchange *ghost row* (*halo row*)
- All processes are to be synchronized such that the next iteration of the computation only happens after all row exchanges are completed

In [7]:
import ipyparallel
c=ipyparallel.Client(profile="mpicluster")
print(c.ids)

[0, 1, 2, 3, 4, 5, 6, 7]


In [8]:
%%px
import numpy as np
from mpi4py import MPI
comm = MPI.COMM_WORLD
rank = comm.Get_rank(); size = comm.Get_size(); N = 24
status = MPI.Status()

local_array = np.full(shape=(int(N / size) + 2, N), fill_value=rank, dtype="int")
full_array = np.zeros(shape=(N + size * 2, N), dtype="int")

comm.Gather(local_array, full_array, root=0)
if rank == 0:
    print (full_array)
if (rank < size - 1):
    print (rank)
    comm.Send(local_array[int(N/size),], dest = rank + 1, tag = 0)
    comm.Recv(local_array[int(N/size) + 1,], source = rank + 1, tag = 0, status = status)
if (rank > 0):
    print (rank)
    comm.Recv(local_array[0,], source = rank - 1, tag = 0, status = status)
    comm.Send(local_array[1,], dest = rank - 1, tag = 0)

comm.Barrier()
comm.Gather(local_array, full_array, root=0)
if rank == 0:
    print (full_array)

[stdout:0] 
4
4
[stdout:1] 
6
6
[stdout:2] 
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
 [3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 

In [9]:
import ipyparallel
c=ipyparallel.Client(profile="mpicluster")
print(c.ids)

[0, 1, 2, 3, 4, 5, 6, 7]


In [10]:
%%px
-

In [5]:
!convert heat.pnm heat.gif

#### <center> The Game of Life </center>

- Board game: theoretically infinite two-dimensional array of cells
- Each cell hold one "organism" and has eight neighboring cells, including those diagonally adjacent
- Initially, some cells occupied

** Rules: **
- two or three neighboring organisms: survives for the next generation
- more than four neighbors: dies from overpopulation
- less than two neighbors: dies from isolation
- Empty cell with exactly three neighbors: spawn new organism

** Serious applications: **
- fluid/gas dynamics
- movement of fluids and gases aroudn objects
- diffusion of gases
- biological growth
- airflow across an airplane wing
- erosion/movement of sand at a beach or riverbank